<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>WinExe</OutputType><TargetFramework>net8.0-windows</TargetFramework><UseWPF>true</UseWPF><Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings><AssemblyName>ValhallaLauncher</AssemblyName><Version>0.4.6</Version></PropertyGroup><ItemGroup><Resource Include="background.png" />
    <Resource Include="launcher-ui.png" /><Content Include="config.json"><CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory></Content><Content Include="Valhalla-Vanilla-26.3.zip"><CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory></Content></ItemGroup><ItemGroup>
  <PackageReference Include="Microsoft.Identity.Client" Version="4.77.1" />
</ItemGroup>
</Project>